---
baseURL: https://www.ruki.es
languageCode: es-es
title: Rūkī
pygmentsstyle: monokai
theme: novela
paginate: "6"
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
